### ISSUE TITLE
Config is lost after update

### ISSUE THREAD

**Issue by brejoc** [btobolaski/docker-owncloud#5]
After an update the config will be gone, because it resides in the config folder. To prevent this, you should add the config folder to the volumes: `VOLUME ["/var/www/owncloud/data", "/var/www/owncloud/config"]`

**Comment by rickyzhang82** [comment]
But the config was created from zip file before your volume is created. So exposing config folder doesn't seem to work. I haven't tried it yet. I'm still working on enabling SSL inside docker.

**Comment by brejoc** [comment]
@rickyzhang82 I'm talking about the owncloud config, not the webserver config. Do you mean the same?

**Comment by rickyzhang82** [comment]
I refer to owncloud config folder. I found that it was created by zipped file. 

Do you confirm it works by making it as external volume?

**Comment by brejoc** [comment]
@rickyzhang82 okay, now I know what you mean. Yes, the folder is created from the zip file. That works for the first time. After you've been entering the database details the config file gets stored in the config folder. But when you are creating a new ownCloud container (due to updates e.g.) the config folder will be lost. This can be prevented with a volume definition for `config`. Take a look at my [fork](https://github.com/brejoc/docker-owncloud).

**Comment by rickyzhang82** [comment]
I see. But I don't follow why config is not persistent in container. Because as long as container didn't wipe out, the config folder should be persistent.

**Comment by brejoc** [comment]
@rickyzhang82 Lets say you are deploying version 8.0.3. But next week version 8.0.4 will be released and you'll be creating a new container. All your files and the database, if you are using MySQL, are safely stored in an other data-container or on the host. Your owncloud-config on the other hand will be lost and has to be recreated on the first start. While this is more of an inconvenience than a show stopper, I'd like to have a more seamless update path.

**Comment by rickyzhang82** [comment]
OK. I see your point. 

I used to installed ubuntu repository owncloud in my ARM board. But it never get updated. Now owncloud had been withdrawn from ubuntu. I have noticed this issues.

I follow your idea and build an owncloud for ARM board. Thanks!

**Comment by btobolaski** [comment]
Should be all set
